"use strict";

const TEXTO_VAZIO = "",
	TEXTO_ESCOLHAPERSONAGEM = "Escolha o personagem",
	TEXTO_NAOPOSSUEITEM = "Não tem esse item.",
	TEXTO_ITEMUSO = "O item ja está em uso.",
	TEXTO_ITEMUSOVARIAS = "Não pode usar o item várias vezes seguidas.",
	TEXTO_VIDAMAXIMA = "A vida ja está no máximo.",
	TEXTO_SALVARSEMJOGAR = "Precisa estar jogando para salvar o jogo.",
	TEXTO_JOGOSALVO = "Jogo salvo.",
	TEXTO_JOGOCARREGADO = "Jogo carregado.",
	TEXTO_NAOEXISTEJOGOSALVO = "Não existe jogo salvo",
	TEXTO_ULTIMOLOCAL = "Esse é o ultimo local.",
	TEXTO_PRIMEIROLOCAL = "Esse é o primeiro local.",
	TEXTO_MUDARMAPABATALHA = "Não pode mudar o local enquanto batalha.",
	TEXTO_JOGADORCRITICO = () => {return `${jogador.nome} deu um golpe crítico.`;},
	TEXTO_INIMIGOCRITICO = () => {return `${inimigo.nome} deu um golpe crítico.`;},
	TEXTO_DERROTADO = () => {return `Você foi derrotado pelo ${inimigo.nome}.`;},
	TEXTO_INIMIGOAPARECEU = () => {return `${inimigo.nome} apareceu.`;},
	TEXTO_DERROTOUINIMIGO = () => {return `Derrotou ${inimigo.nome}. Ganhou ${experienciaGanha} de experiência.`;},
	TEXTO_DERROTOUINIMIGOITEM = () => {return `Derrotou ${inimigo.nome}. Ganhou ${ITENS[inimigo.item].nome} e ${experienciaGanha} de experiência.`;},
	TEXTO_ITEMENCONTRAR = () => {return `${jogador.nome} encontrou 1 ${ITENS[sorteioItem].nome}.`;};